advertised:
  host:
    name: localhost

management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
  health:
    kafka:
      enabled: true

kafka:
  brokers:
    urls: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumerGroup: ${KAFKA_CONSUMER_GROUP_ID:MS001}
  autoOffset: ${KAFKA_CONSUMER_OFFSET:earliest}
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
    username: ${KAFKA_USERNAME:USERNAME}
    password: ${KAFKA_PASSWORD:PASSWORD}
    mechanism: ${KAFKA_SECURITY_MECHANISM:SCRAM-SHA-512}
