advertised:
  host:
    name: localhost

management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
  health:
    kafka:
      enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${MAIN_POSTGRES_HOST:localhost}:${MAIN_POSTGRES_PORT:5432}/${MAIN_POSTGRES_DB:kafka-poc}
    username: ${MAIN_POSTGRES_USER:postgres}
    password: ${MAIN_POSTGRES_PASSWORD:postgres}
    hikari:
      connectionTimeout: ${HIKARI_CONNECTION_TIMEOUT:20000}
      minimumIdle: ${MINIMUM_IDLE:5}
      maximumPoolSize: ${MAXIMUM_POOL_SIZE:300}
      idleTimeout: ${IDLE_TIMEOUT:740000}
      maxLifetime: ${MAX_LIFETIME:1740000}
  liquibase:
    enabled: true
    change-log: db.changelog-master.xml

kafka:
  brokers:
    urls: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumerGroup: ${KAFKA_CONSUMER_GROUP_ID:MS001}
  autoOffset: ${KAFKA_CONSUMER_OFFSET:earliest}
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
    username: ${KAFKA_USERNAME:USERNAME}
    password: ${KAFKA_PASSWORD:PASSWORD}
    mechanism: ${KAFKA_SECURITY_MECHANISM:SCRAM-SHA-512}
