server:
  port: 8083

advertised:
  host:
    name: localhost

management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
  health:
    kafka:
      enabled: true

kafka:
  brokers:
    broker1:
      url: localhost:9092
  consumerGroup: cgroup
  autoOffset: earliest
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
    username: ${KAFKA_USERNAME:USERNAME}
    password: ${KAFKA_PASSWORD:PASSWORD}
    mechanism: ${KAFKA_SECURITY_MECHANISM:SCRAM-SHA-512}
